{% set version = "0.2.6" %}

package:
  name: uv
  version: {{ version }}

source:
  fn: uv-{{ version }}.tar.gz
  url: https://github.com/astral-sh/uv/releases/download/{{ version }}/source.tar.gz
  sha256: c822fc118367829825775874c19d14bb9415804a2c5efa6dfbb302b1fb18ae0e
  patches:
    - 0000-no-link-static-vc-runtime.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make

test:
  requires:
    - m2-grep  # [win]
  commands:
    - uv --version
    - uv --help
    - uv --version | grep -iE "{{ version.replace('.', '\.') }}"

about:
  home: https://github.com/astral-sh/uv
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An extremely fast Python package installer and resolver, written in Rust.

extra:
  recipe-maintainers:
    - charliermarsh
    - bollwyvl
