# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.6.17"

package:
  name: uv
  version: ${{ version }}

source:
  url: https://github.com/astral-sh/uv/releases/download/${{ version }}/source.tar.gz
  sha256: 02485f87eabd48fde185c7d0f3402b2c95963b87b054139a1e0e4a3a8c20fb79
  patches:
    - 0000-no-link-static-vc-runtime.patch

build:
  number: 1
  script:
    file: build-uv
    env:
      # This env var specifies the base 2 log of the allocator page size
      JEMALLOC_SYS_WITH_LG_PAGE: ${{ "16" if target_platform == "linux-aarch64" or target_platform == "linux-ppc64le" }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - uv --version
      - uv --help
      - uv --version | grep -iE "${{ version | replace('.', '\\.') }}"

about:
  homepage: https://github.com/astral-sh/uv
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An extremely fast Python package installer and resolver, written in Rust.
  documentation: https://docs.astral.sh/uv

extra:
  recipe-maintainers:
    - charliermarsh
    - bollwyvl
