# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "0.8.11"

package:
  name: uv
  version: ${{ version }}

source:
  url: https://github.com/astral-sh/uv/releases/download/${{ version }}/source.tar.gz
  sha256: b4d8b28ef2d4123ec0b6c254416be5ede5fffcb3bb9d136bb9b493137aca9917
  patches:
    - 0000-no-link-static-vc-runtime.patch
    - 0001-no-writeln-space-colon.patch

build:
  number: 0
  script:
    file: build-uv
    env:
      # This env var specifies the base 2 log of the allocator page size
      JEMALLOC_SYS_WITH_LG_PAGE: ${{ "16" if target_platform == "linux-aarch64" or target_platform == "linux-ppc64le" }}
      # used in `build-uv.sh` to verity the expected version of rust
      CBC_RUST_VERSION: ${{ rust_compiler_version | default(".*") }}

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ compiler("rust") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - cmake
    - make

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - uv --version
      - uv --help
      - uv --version | grep -iE "${{ version | replace('.', '\\.') }}"

about:
  homepage: https://github.com/astral-sh/uv
  license: Apache-2.0 OR MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: An extremely fast Python package installer and resolver, written in Rust.
  documentation: https://docs.astral.sh/uv

extra:
  recipe-maintainers:
    - charliermarsh
    - bollwyvl
