azure:
  free_disk_space: true
  settings_linux:
    swapfile_size: 22GiB
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
  upload_packages: true
bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
  win_arm64: win_64
conda_build:
  error_overlinking: false
conda_build_tool: rattler-build
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
shellcheck:
  enabled: true
test: native_and_emulated
