bot:
  automerge: true
azure:
  upload_packages: true
  settings_linux:
    swapfile_size: 10GiB
  settings_win:
    variables:
      SET_PAGEFILE: 'True'
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
conda_build:
  # See https://github.com/conda-forge/rust-activation-feedstock/issues/58
  # error_overlinking: true
  error_overlinking: false
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
